config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'posts#index'
  # root to: 'pages#homepage'
  # get '/', to:'pages#homepage'
  root 'pages#homepage'
  # (alternative way here)

  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  resources :users do
    member do
      get :followings
      get :followers
    end
  end

  resources :posts do
    resources :comments
  end

  resources :relationships
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :post_photo
  has_many :comments, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'

  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  has_one_attached :avatar

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'following_id', dependent: :destroy

  has_many :followings, through: :active_relationships
  has_many :followers, through: :passive_relationships

  validates :username, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if params[:user_id]
      user = User.find(params[:user_id])
    end
    post = Post.find(params[:post_id])
    comment = post.comments.create(comment_params.merge(user_id: current_user.id))
    if comment.save
      if user
        redirect_to user_path(user), notice: 'Comment success'
      else
        redirect_to post_path(post)
      end
    else
      if user
      redirect_to user_path(user), alert: 'There was an error.'
    else
      redirect_to post_path(post)
    end
  end
end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to user_path(current_user)
    else
      render user_path(current_user), notice:'Your post was successfully created.'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user), notice:'Your post has been deleted.'
  end

  def edit
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def update
    # update the edit post so that can redirect to the previous show page
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.save
      redirect_to user_path(current_user)
    else
      render user_path(current_user), notice:'Your post was successfully created.'
    end
  end

  private

    def post_params
      params.require(:post).permit(:caption, :post_photo)
    end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:following_id])
    current_user.active_relationships.create(following_id: user.id)
    redirect_to user_path(user)
  end

  def destroy
    relationship = Relationship.find(params[:id])
    user = relationship.following
    relationship.destroy
    redirect_to user_path(user)
  end

end

app/controllers/sessions_controller.rb
#this related to login path

class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in(user)
      redirect_to user_path(user)
    else
      render 'new'
    end
  end

  def destroy
    # if change to destroy, will not work
    log_out
    redirect_to root_path, notice: 'You have logged out'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    user = User.new
  end

  def create
    user = User.create(user_params)

    if user.save
      log_in(user)
      redirect_to user_path(user)
    else
      render :new
  end
end

def edit
  @user = User.find(params[:id])
end

def update
  user = User.find(params[:id])
  user.update(user_params)
  if user.save
    redirect_to user_path(user), notice:'Updated'
  else
    render :edit
  end

  # current_user.update(user_params)
  # redirect_to current_user

end

def show
  @user = User.find(params[:id])
  @comment = Comment.new

  @find_relationship = current_user.active_relationships.find_by(following_id: @user.id)
  # @find_relationship = Relationship.find(3)

end

def destroy
end

def followings
  @user = User.find(params[:id])
end

def followers
  @user = User.find(params[:id])
end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a63389bb90.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/homepage.html.erb
<div class="relative">

  <%= image_tag 'front.png', width: 800, id: 'iphone', class: 'absolute' %>

  <div class="text-center absolute" id='igLogo'>
  <%= image_tag 'text 1.png', width: 200 %>
  </div>

<%= form_with(url:login_path) do |f| %>

<div class="text-center absolute" id="field">
<%= f.label :email %>
<%= f.text_field :email %>
</div>

<div class="text-center absolute" id="password">
<%= f.label :password %>
<%= f.password_field :password %>
</div>

<div class="text-center absolute" id="login">
<%# <%= link_to 'Login', login_path %>
<%= f.submit 'Login' %>
</div>

<% end %>

<div class="text-center absolute" id="signup">
<p>Don't have an account? <%= link_to 'Sign Up', new_user_path %></p>
</div>
<%# <%= link_to 'about', about_path %>

</div>

app/views/posts/edit.html.erb
<h1>Edit your posts, <%= @user.username %></h1>

<%= form_for @post do |f| %>
<%= f.file_field :post_photo %>
<%= f.text_field :caption, placeholder:'Caption' %>
<%= f.submit 'Post' %>
<% end %>

<%= image_tag @post.post_photo, style: "width: 800px; display: block;" %>
<%= @post.caption %>

app/views/posts/show.html.erb
  <%= image_tag @post.post_photo, style: "width: 800px; display: block;" %>
  <%= @post.caption %>

  <%= form_for ([@post, @comment]) do |f| %>
    <%= f.text_field :content %>
    <%= f.submit 'Comment'%>
  <% end %>

  <% @post.comments.each do |comment| %>
    <%= comment.user.username %>
    <%= comment.content %>
    <br>
  <% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <% if logged_in? %>
      <%= link_to current_user, class: 'navbar-brand' do %>
        <%= image_tag 'text 1.png', width: 100 %>
      <% end %>

      <%# <% else %>

      <%# <%= link_to root_path, class: 'navbar-brand' do %>
        <%# <%= image_tag 'text 1.png', width: 100 %>
      <%# <% end %>

    <% end %>
  </div>
  <div>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <% if logged_in? %>
          <div class="btn-group">
            <button>
              <%= link_to 'Settings', edit_user_path(current_user) %>
            </button>


            <button>
              <%= link_to 'Logout', logout_path, method: :delete %>
            </button>

            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search for users" aria-label="Search">
                <div class="btn-group">
                  <button type="submit">Search</button>
                </div>
            </form>
         <!-- <a class="nav-link active" aria-current="page" href="#">Settings</a> -->
            <%# <% else %>

            <!-- <div class="btn-group">
            <button>
              <%# <%= link_to 'Login', login_path %> %>
            </button>

            <button>
              <%# <%= link_to 'Sign Up', new_user_path %> %>
            </button> -->

          </div>
        <% end %>
      </li>
    </ul>

  </div>
</nav>

app/views/users/edit.html.erb
<h1>Settings</h1>
<p>Current username: <%= @user.username %></p>
<p>Update your profile picture</p>
<%= form_for @user do |f| %>
<%= f.file_field :avatar %>
<br>
<%= f.submit 'Upload' %>
<% end %>

app/views/users/followers.html.erb
<h1><%= @user.username %>'s followers </h1>
<% @user.followers.each do |user| %>
<%= link_to "#{user.username}", user_path(user) %>
<% end %>

app/views/users/followings.html.erb
<h1><%= @user.username %>'s followings </h1>
<% @user.followings.each do |user| %>
<%= link_to "#{user.username}", user_path(user) %>
<% end %>

app/views/users/new.html.erb
<div class="signup-form">

  <%= form_for User.new do |f| %>


    <!-- <i class="fas fa-check-circle"></i>
    <i class="fas fa-exclamation-circle"></i> -->


  <div id="formErrors"></div>

  <%= f.label :username %>
  <%= f.text_field :username, required: true %>

  <%= f.label :email %>
  <%= f.text_field :email, required: true %>
  <!-- <i class="fas fa-check-circle"></i>
  <i class="fas fa-exclamation-circle"></i> -->

  <%= f.label :password %>
  <%= f.password_field :password, required: true %>
  <!-- <i class="fas fa-check-circle"></i>
  <i class="fas fa-exclamation-circle"></i> -->

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, required: true %>
  <!-- <i class="fas fa-check-circle"></i>
  <i class="fas fa-exclamation-circle"></i> -->

<%= f.submit 'Signup',  data: { disable_with: false } %>

<% end %>

</div>

<div class="btn-group">
  <button>
  <%= link_to 'Back', root_path %>
  </button>
</div>

app/views/users/show.html.erb
<h1>Welcome back, <%= current_user.username %>
<br>
  <%# <%= @user.username %>
<br>
<% if @user.avatar.attached? %>
  <%= image_tag @user.avatar, style: 'width: 500px;' %>
<% end %>
<br>
  <%= link_to 'Edit Profile', edit_user_path(@user) %>
<br>
  <%= link_to "#{@user.followings.count} Followings", followings_user_path(@user) %>
  <%= link_to "#{@user.followers.count} Followers", followers_user_path(@user) %>

  <% if current_user != @user %>

  <% if current_user.followings.include?(@user) %>

    <%= form_for @find_relationship, html: {method: :delete} do |f| %>
      <%= f.submit 'Unfollow' %>
    <% end %>

      <% else %>

    <%= form_for Relationship.new do |f| %>
      <%= hidden_field_tag :following_id, @user.id %>
      <%= f.submit 'Follow' %>
    <% end %>

  <% end %>
<% end %>

<h2>Timeline</h2>

  <% if current_user == @user %>
<%= form_for Post.new do |f| %>
  <%= f.file_field :post_photo %>
  <%= f.text_field :caption, placeholder:'Caption' %>
  <%= f.submit 'Post' %>
<% end %>
<% end %>

<% @user.posts.each do |post| %>
  <%= image_tag post.post_photo, style: "width: 800px; display: block;" %>
  <%= post.caption %>

  <%= form_for ([post, @comment]) do |f| %>
  <%= hidden_field_tag "user_id", @user.id %>
    <%= f.text_field :content %>
    <%= f.submit 'Comment'%>
  <% end %>

  <% post.comments.each do |comment| %>
    <%= comment.user.username %>
    <%= comment.content %>
    <br>
  <% end %>
<br>


  <%= link_to 'Show', post_path(post) %>

  <% if current_user == @user %>
  <%= link_to 'Edit', edit_post_path(post) %>
  <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure you want to delete?' } %>
<% end %>

<% end %>